### ISSUE TITLE
Running Compiled Jar File Causes ExceptionInInitializerError

### ISSUE THREAD

**Issue by clov0** [uncomplicate/fluokitten#23]
On `[org.clojure/clojure "1.8.0"]` and using `:uberjar {:aot :all}`
I'm using the `clojure:onbuild` docker image it runs on openjdk 8 using the `openjdk:8-alpine` image and leiningen 2.7.1
Running the jar file causes

```java
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(java.base@9-internal/Native Method)
	at java.lang.Class.forName(java.base@9-internal/Class.java:378)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at uncomplicate.fluokitten.core$loading__5569__auto____3776.invoke(core.clj:9)
	at uncomplicate.fluokitten.core__init.load(Unknown Source)
	at uncomplicate.fluokitten.core__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(java.base@9-internal/Native Method)
	at java.lang.Class.forName(java.base@9-internal/Class.java:378)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:2088)
	at stellar.access.samples.consumer$loading__5569__auto____2873.invoke(consumer.clj:1)
	at stellar.access.samples.consumer__init.load(Unknown Source)
	at stellar.access.samples.consumer__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(java.base@9-internal/Native Method)
	at java.lang.Class.forName(java.base@9-internal/Class.java:378)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.Util.loadWithClass(Util.java:250)
	at stellar.access.samples.consumer.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: clojure.core.reducers.CollFold
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-internal/BuiltinClassLoader.java:366)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@9-internal/ClassLoaders.java:184)
	at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:419)
	at java.lang.Class.forName0(java.base@9-internal/Native Method)
	at java.lang.Class.forName(java.base@9-internal/Class.java:378)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at uncomplicate.fluokitten.algo__init.__init2(Unknown Source)
	at uncomplicate.fluokitten.algo__init.<clinit>(Unknown Source)
	... 70 more
```

project.clj : 

```clojure
(defproject stellar/access "0.1.0-SNAPSHOT"
  :description "Panel Data Collection"

  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}

  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/core.async "0.3.443"]
                 [org.clojure/algo.monads "0.1.6"]
                 [uncomplicate/fluokitten "0.6.0"]
                 ;--------------------------------Formats
                 [cheshire "5.7.1"]
                 [org.clojure/data.csv "0.1.4"]
                 [semantic-csv "0.2.1-alpha1"]
                 ;--------------------------------Time
                 [clj-time "0.13.0"]
                 [jarohen/chime "0.2.2"]
                 [tick "0.2.4"]
                 ;--------------------------------Technology
                 [com.novemberain/langohr "3.7.0"]
                 [com.novemberain/monger  "3.1.0"]
                 [org.slf4j/slf4j-nop "1.7.12"]    ;) To stop mongo.java logs
                 ;--------------------------------Loggin-and-Profiling
                 [com.taoensso/timbre "4.10.0"]
                 [com.taoensso/tufte "1.1.1"]
                 ;--------------------------------For-Eastwood-Vim-Linter
                 [jonase/eastwood "0.2.4" :exclusions [org.clojure/clojure]]
                 ;--------------------------------For-Fireplace-??
                 [cider/cider-nrepl "0.14.0"]
                 [lein-cljfmt "0.5.6"]
                 ;--------------------------------
                 [danlentz/clj-uuid "0.1.7"]
                 [random-seed "1.0.0"]
                 ]

  :test-paths   ["test"]
  :aliases      {"itest" ["midje" ":filters" "it"]
                 "utest" ["midje" ":filters" "-it"]
                 "test"  ["midje"]}

  :plugins      [[cider/cider-nrepl "0.14.0"]
                 [venantius/ultra "0.5.1"]
                 [jonase/eastwood "0.2.4"]
                 [venantius/yagni "0.1.4"]
                 [lein-cljfmt "0.5.6"]
                 [lein-midje "3.2.1"]]

  :repl-options {:host "0.0.0.0" :port 34567}
  :main nil
  :target-path "target/%s"

  :jvm-opts ["-Xmx2g" "-Xms512m" "-XX:+UseConcMarkSweepGC"]
  :profiles {:uberjar {:aot :all}
             :dev     {:dependencies [[midje "1.8.3"]
                                      [jonase/eastwood "0.2.4" :exclusions [org.clojure/clojure]]]}})
```

**Comment by blueberry** [comment]
Can you please share the simple project.clj that demonstrate this, as well as more details about JDK (type, version, etc.) and the operating system?

**Comment by clov0** [comment]
Sorry
Yeah
I edited the main post

**Comment by blueberry** [comment]
Thanks. I meant can you share it as a project (including the directory structure and a simple code that demonstrates the exception) so I could try it on my system? Removing other libraries and just having the minimal project that fails would also help.

**Comment by clov0** [comment]
Oh .. sure
I created a trimmed down sample repo and shared it with you
Thanks

**Comment by blueberry** [comment]
What should I type in the shell to try it?

**Comment by clov0** [comment]
`lein uberjar` and then ` java -cp target/uberjar/access-0.1.0-SNAPSHOT-standalone.jar stellar.access.samples.consumer`

**Comment by blueberry** [comment]
I can confirm that I get the same results (Caused by: java.lang.ClassNotFoundException: clojure.core.reducers.CollFold) but I do not know what might be the problem.

There was a similar issue with Schema https://github.com/plumatic/schema/issues/354
They suggest to explicitly add transitive dependencies to :aot.

Since the issue is in the loading of a clojure core class, I am not sure what to suggest.

Anyway, If you find the solution, and it can be included in Fluokitten core, I'll gladly do it.

**Comment by blueberry** [comment]
Also note that your uberjar does not contain the offending Clojure class clojure.core.reducers.CollFold (as far as I see), so this might be the problem: CollFold is not being AOT comipiled. If that is so (I am not 100% sure), this might be not the problem with Fluokitten, fluokitten just discovered the underlying problem with the missing CollFold.

**Comment by blueberry** [comment]
It seems to not be connected to Fluokitten, but the lein/aot thing that you should investigate:

https://groups.google.com/forum/#!topic/clojure/bW7BwsfYKeI
